name: Deploy Rails App with Nginx

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy Rails App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: docker buildx create --use

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          docker login -u elviajero34 -p $DOCKERHUB_PASSWORD
          docker buildx build --platform linux/arm/v7 \
          --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY \
          --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE \
          --tag elviajero34/race:latest . \
          --push
      
      # Transfer docker-compose.yml and nginx.conf to Raspberry Pi
      - name: Transfer docker-compose.yml to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          # Transfer the docker-compose.yml file to the Raspberry Pi
          sshpass -p $RASPBERRY_PI_PASSWORD scp -o StrictHostKeyChecking=no docker-compose.yml pi@$RASPBERRY_PI_IP:/var/www/html/race/
      - name: Transfer nginx.conf to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          # Transfer the nginx.conf file to the Raspberry Pi
          sshpass -p $RASPBERRY_PI_PASSWORD scp -o StrictHostKeyChecking=no nginx.conf pi@$RASPBERRY_PI_IP:/var/www/html/race/

      # Pull the latest image from Docker Hub
      - name: Pull the latest image from Docker Hub
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=120 -o ServerAliveCountMax=100 pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Pull the latest image from Docker Hub
            echo "Pulling the latest Docker image from Docker Hub..."
            if ! docker pull elviajero34/race:latest; then
              echo "Failed to pull Docker image from Docker Hub."
              exit 1
            fi
          EOF

      # Remove old images except for the latest
      - name: Remove old images except for the latest
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=120 -o ServerAliveCountMax=100 pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Remove old images except for the latest
            echo "Cleaning up old Docker images..."
            docker image prune -af --filter "label!=maintainer=elviajero34" || true
          EOF

      # Stopping and removing old containers
      - name: Stopping and removing old containers
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=120 -o ServerAliveCountMax=100 pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Navigate to the app directory
            echo "Navigating to the app directory..."
            cd /var/www/html/race

            # Stop and remove old containers
            echo "Stopping and removing old containers..."
            docker-compose down --remove-orphans || true
          EOF

      # Starting new container
      - name: Starting new container
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=120 -o ServerAliveCountMax=100 pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Navigate to the app directory
            echo "Navigating to the app directory..."
            cd /var/www/html/race

            # Start the new containers
            echo "Starting the new containers..."
            docker-compose up -d
          EOF

      # Running database migrations
      - name: Running database migrations
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no \
          -o ServerAliveInterval=120 -o ServerAliveCountMax=100 pi@$RASPBERRY_PI_IP \
          "bash -s" << 'EOF'
            # Navigate to the app directory
            echo "Navigating to the app directory..."
            cd /var/www/html/race
          
            # Check the status of the containers
            echo "Checking the status of the containers..."
            docker ps
          
            # Create a new database if it doesn't exist
            echo "Creating a new database..."
            docker exec race-app-1 bundle exec rake db:create RAILS_ENV=production
          
            # Run database migrations
            echo "Running database migrations..."
            docker exec race-app-1 bundle exec rake db:migrate RAILS_ENV=production
          EOF